// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAraurjZGn2ijbGR4EYBLzLkNdCO_LhpqI',
    appId: '1:1066608692627:web:ee6e020335b2d5704aac66',
    messagingSenderId: '1066608692627',
    projectId: 'newapp-55624',
    authDomain: 'newapp-55624.firebaseapp.com',
    storageBucket: 'newapp-55624.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuM2utciA9x9SzGwootvtzRW0HZZZdkWE',
    appId: '1:1066608692627:android:52aa967c1814a4ad4aac66',
    messagingSenderId: '1066608692627',
    projectId: 'newapp-55624',
    storageBucket: 'newapp-55624.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzLr7UaYLBrKH1KjC2on8Skx0u0pskgXg',
    appId: '1:1066608692627:ios:3eb87c1b356430a64aac66',
    messagingSenderId: '1066608692627',
    projectId: 'newapp-55624',
    storageBucket: 'newapp-55624.appspot.com',
    iosBundleId: 'com.example.chattingapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzLr7UaYLBrKH1KjC2on8Skx0u0pskgXg',
    appId: '1:1066608692627:ios:092abafd8c2ff2e04aac66',
    messagingSenderId: '1066608692627',
    projectId: 'newapp-55624',
    storageBucket: 'newapp-55624.appspot.com',
    iosBundleId: 'com.example.chattingapp.RunnerTests',
  );
}
